# Create mock dataset to emulate articles.csv schema
make_mock_df <- function(n = 80, seed = 1) {
  set.seed(seed)
  df <- data.frame(
    url = sprintf("http://x/%03d", 1:n),
    timedelta = sample(1:60, n, replace = TRUE),
    weekday_is_sunday = sample(0:1, n, replace = TRUE),
    is_weekend = sample(0:1, n, replace = TRUE),
    data_channel_is_lifestyle = sample(0:1, n, TRUE),
    data_channel_is_entertainment = sample(0:1, n, TRUE),
    data_channel_is_bus = sample(0:1, n, TRUE),
    data_channel_is_socmed = sample(0:1, n, TRUE),
    data_channel_is_tech = sample(0:1, n, TRUE),
    data_channel_is_world = sample(0:1, n, TRUE),
    weekday_is_monday    = sample(0:1, n, TRUE),
    weekday_is_tuesday   = sample(0:1, n, TRUE),
    weekday_is_wednesday = sample(0:1, n, TRUE),
    weekday_is_thursday  = sample(0:1, n, TRUE),
    weekday_is_friday    = sample(0:1, n, TRUE),
    weekday_is_saturday  = sample(0:1, n, TRUE),
    n_tokens_title = rpois(n, 12),
    n_tokens_content = rpois(n, 400),
    n_unique_tokens = runif(n, 0.1, 1),
    n_non_stop_words = runif(n, 0.1, 1),
    n_non_stop_unique_tokens = runif(n, 0.1, 1),
    num_hrefs = rpois(n, 10),
    num_self_hrefs = rpois(n, 2),
    num_imgs = rpois(n, 3),
    num_videos = rpois(n, 1),
    average_token_length = runif(n, 3, 6),
    num_keywords = rpois(n, 10),
    kw_min_min = rnorm(n, 0, 1),
    kw_max_min = rnorm(n, 0, 1),
    kw_avg_min = rnorm(n, 0, 1),
    kw_min_max = rnorm(n, 2, 1),
    kw_max_max = rnorm(n, 5, 2),
    kw_avg_max = rnorm(n, 3, 1),
    kw_min_avg = rnorm(n, 0.5, 1),
    kw_max_avg = rnorm(n, 2.5, 1),
    kw_avg_avg = rnorm(n, 1.5, 0.8),
    self_reference_min_shares = rpois(n, 30),
    self_reference_max_shares = rpois(n, 300),
    self_reference_avg_sharess = rpois(n, 100),
    LDA_00 = runif(n), LDA_01 = runif(n), LDA_02 = runif(n), LDA_03 = runif(n), LDA_04 = runif(n),
    global_subjectivity = runif(n),
    global_sentiment_polarity = runif(n, -1, 1),
    global_rate_positive_words = runif(n),
    global_rate_negative_words = runif(n),
    rate_positive_words = runif(n),
    rate_negative_words = runif(n),
    avg_positive_polarity = runif(n),
    min_positive_polarity = runif(n, 0, 0.3),
    max_positive_polarity = runif(n, 0.7, 1),
    avg_negative_polarity = runif(n, -0.5, 0),
    min_negative_polarity = runif(n, -1, -0.7),
    max_negative_polarity = runif(n, -0.3, 0),
    title_subjectivity = runif(n),
    title_sentiment_polarity = runif(n, -1, 1),
    abs_title_subjectivity = runif(n),
    abs_title_sentiment_polarity = abs(runif(n, -1, 1))
  )
  df$shares <- with(df, 50 + 2*num_hrefs + 5*data_channel_is_tech - 3*num_videos + rnorm(n, 0, 30))
  df
}
